select DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from(
    select USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    from ONLINE_SALE
    where SALES_DATE like "2022-03-%"
    UNION ALL
    select NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    from OFFLINE_SALE
    where SALES_DATE like "2022-03-%"
) as total_sale
order by SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC