SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, round(AVG(REVIEW_SCORE), 2) as SCORE
FROM REST_INFO join REST_REVIEW on REST_INFO.REST_ID = REST_REVIEW.REST_ID
group by REST_INFO.REST_ID
having ADDRESS like "서울%"
order by SCORE DESC, FAVORITES DESC